package com.weekly.plan.service;

/**
 * Source classification for AI-suggested commits generated by {@link DraftFromHistoryService}.
 */
public enum CommitSource {
    /** Commit was not completed (status != DONE) in the most recent reconciled plan. */
    CARRIED_FORWARD,
    /** Commit title or outcome ID appeared in two or more consecutive historical weeks. */
    RECURRING,
    /** Commit addresses a coverage gap — reserved for future {@code NextWorkService} integration. */
    COVERAGE_GAP
}
