package com.weekly.plan.service;

import com.weekly.plan.domain.ChessPriority;
import com.weekly.compatibility.dualwrite.DualWriteService;
import com.weekly.plan.domain.CommitCategory;
import com.weekly.plan.domain.CompletionStatus;
import com.weekly.plan.domain.PlanState;
import com.weekly.plan.domain.WeeklyCommitActualEntity;
import com.weekly.plan.domain.WeeklyCommitEntity;
import com.weekly.plan.domain.WeeklyPlanEntity;
import com.weekly.plan.repository.WeeklyCommitActualRepository;
import com.weekly.plan.repository.WeeklyCommitRepository;
import com.weekly.plan.repository.WeeklyPlanRepository;
import com.weekly.shared.ErrorCode;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Service that generates an AI-assisted draft plan from the user's planning history.
 *
 * <p>Loads the last {@value #HISTORY_WEEKS} weeks of plans and commits, identifies
 * carried-forward items and recurring patterns, and creates a pre-filled DRAFT plan
 * for the target week.
 *
 * <p>Sources of suggestions:
 * <ul>
 *   <li>{@link CommitSource#CARRIED_FORWARD} — commits not completed in the most recent
 *       reconciled plan (completion status != DONE)</li>
 *   <li>{@link CommitSource#RECURRING} — commits whose title (normalized Levenshtein
 *       distance &lt; {@value #SIMILARITY_THRESHOLD}) or outcome ID appeared in 2+
 *       consecutive historical weeks</li>
 *   <li>{@link CommitSource#COVERAGE_GAP} — reserved for future {@code NextWorkService}
 *       integration; none generated by this service at present</li>
 * </ul>
 */
@Service
public class DraftFromHistoryService {

    /** Number of historical weeks to load and analyze. */
    static final int HISTORY_WEEKS = 4;

    /**
     * Normalized Levenshtein distance threshold for title similarity.
     * Two commit titles are considered similar when their normalized distance
     * is strictly less than this value.
     */
    static final double SIMILARITY_THRESHOLD = 0.3;

    private final WeeklyPlanRepository planRepository;
    private final WeeklyCommitRepository commitRepository;
    private final WeeklyCommitActualRepository actualRepository;
    private final DualWriteService dualWriteService;

    public DraftFromHistoryService(
            WeeklyPlanRepository planRepository,
            WeeklyCommitRepository commitRepository,
            WeeklyCommitActualRepository actualRepository,
            DualWriteService dualWriteService
    ) {
        this.planRepository = planRepository;
        this.commitRepository = commitRepository;
        this.actualRepository = actualRepository;
        this.dualWriteService = dualWriteService;
    }

    /**
     * Generates a pre-filled DRAFT plan for the target week from the user's planning history.
     *
     * <p>If a DRAFT plan already exists for the target week its commits are augmented.
     * If the target plan exists but is no longer in DRAFT state a
     * {@link PlanStateException} is thrown.
     *
     * @param orgId     the organisation ID
     * @param userId    the user for whom to generate a draft
     * @param weekStart the Monday of the target week (must be a Monday)
     * @return the created/updated draft plan ID and the suggested commit list
     * @throws PlanValidationException if {@code weekStart} is not a Monday
     * @throws PlanStateException      if the target week already has a non-DRAFT plan
     */
    @Transactional
    public DraftFromHistoryResult draftFromHistory(UUID orgId, UUID userId, LocalDate weekStart) {
        validateWeekStart(weekStart);

        // Load last N weeks of historical plans (excluding the target week itself)
        LocalDate windowEnd = weekStart.minusWeeks(1);
        LocalDate windowStart = weekStart.minusWeeks(HISTORY_WEEKS);
        List<WeeklyPlanEntity> historicalPlans = planRepository
                .findByOrgIdAndOwnerUserIdAndWeekStartDateBetweenOrderByWeekStartDateAsc(
                        orgId, userId, windowStart, windowEnd);

        // Create or get the DRAFT plan for the target week
        WeeklyPlanEntity draftPlan = getOrCreateDraftPlan(orgId, userId, weekStart);
        List<WeeklyCommitEntity> existingDraftCommits = Optional.ofNullable(
                commitRepository.findByOrgIdAndWeeklyPlanId(orgId, draftPlan.getId())
        ).orElse(List.of());

        if (historicalPlans.isEmpty()) {
            return new DraftFromHistoryResult(draftPlan.getId(), List.of());
        }

        // Load commits for all historical plans in a single query
        List<UUID> planIds = historicalPlans.stream().map(WeeklyPlanEntity::getId).toList();
        List<WeeklyCommitEntity> allHistoricalCommits =
                commitRepository.findByOrgIdAndWeeklyPlanIdIn(orgId, planIds);
        Map<UUID, List<WeeklyCommitEntity>> commitsByPlanId = allHistoricalCommits.stream()
                .collect(Collectors.groupingBy(WeeklyCommitEntity::getWeeklyPlanId));

        List<SuggestedCommit> suggestions = new ArrayList<>();
        Set<String> suggestedTitles = new HashSet<>();
        Set<String> suggestedOutcomeIds = new HashSet<>();
        existingDraftCommits.forEach(commit -> recordSuggestionKey(
                commit.getTitle(), commit.getOutcomeId(), suggestedTitles, suggestedOutcomeIds
        ));

        // (1) Carried-forward: commits not completed in most recent reconciled plan
        collectCarriedForwardSuggestions(orgId, historicalPlans, commitsByPlanId,
                suggestions, suggestedTitles, suggestedOutcomeIds);

        // (2) Recurring: commit patterns appearing in 2+ consecutive weeks
        collectRecurringSuggestions(historicalPlans, commitsByPlanId,
                suggestions, suggestedTitles, suggestedOutcomeIds);

        // (3) Persist suggested commits to the draft plan
        List<SuggestedCommit> persistedSuggestions = new ArrayList<>();
        for (SuggestedCommit suggestion : suggestions) {
            WeeklyCommitEntity commit = new WeeklyCommitEntity(
                    UUID.randomUUID(), orgId, draftPlan.getId(), suggestion.title()
            );
            commit.setDescription(
                    suggestion.description() != null ? suggestion.description() : "");
            if (suggestion.chessPriority() != null) {
                commit.setChessPriority(ChessPriority.valueOf(suggestion.chessPriority()));
            }
            if (suggestion.category() != null) {
                commit.setCategory(CommitCategory.valueOf(suggestion.category()));
            }
            if (suggestion.outcomeId() != null) {
                commit.setOutcomeId(UUID.fromString(suggestion.outcomeId()));
            }
            if (suggestion.nonStrategicReason() != null) {
                commit.setNonStrategicReason(suggestion.nonStrategicReason());
            }
            commit.setExpectedResult(
                    suggestion.expectedResult() != null ? suggestion.expectedResult() : "");
            // Store the suggestion source in tags for traceability
            commit.setTagsFromArray(
                    new String[]{"draft_source:" + suggestion.source().name()});
            // Phase 6 dual-write: prepare crosswalk before save (avoids double-save)
            UUID draftIssueId = null;
            WeeklyCommitEntity draftSourceCommit = null;

            if (suggestion.source() == CommitSource.CARRIED_FORWARD
                    && suggestion.sourceCommitId() != null) {
                draftSourceCommit =
                        commitRepository.findById(suggestion.sourceCommitId()).orElse(null);
                if (draftSourceCommit != null) {
                    dualWriteService.prepareCarryForward(commit, draftSourceCommit);
                } else {
                    draftIssueId = dualWriteService.createIssueForCommit(commit, orgId, userId);
                    if (draftIssueId != null) {
                        commit.setSourceIssueId(draftIssueId);
                    }
                }
            } else {
                draftIssueId = dualWriteService.createIssueForCommit(commit, orgId, userId);
                if (draftIssueId != null) {
                    commit.setSourceIssueId(draftIssueId);
                }
            }

            WeeklyCommitEntity savedCommit = commitRepository.save(commit);

            // Create assignment after commit is in DB
            if (draftSourceCommit != null) {
                dualWriteService.finalizeCarryForward(
                        savedCommit, draftSourceCommit, draftPlan.getId(), orgId);
            } else if (draftIssueId != null) {
                dualWriteService.createAssignmentForCommit(
                        draftIssueId, draftPlan.getId(), savedCommit, orgId);
            }

            persistedSuggestions.add(toSuggestedCommit(savedCommit, suggestion.source()));
        }

        return new DraftFromHistoryResult(draftPlan.getId(), persistedSuggestions);
    }

    // ── Carried-forward detection ─────────────────────────────────────────────

    private void collectCarriedForwardSuggestions(
            UUID orgId,
            List<WeeklyPlanEntity> sortedPlans,
            Map<UUID, List<WeeklyCommitEntity>> commitsByPlanId,
            List<SuggestedCommit> suggestions,
            Set<String> suggestedTitles,
            Set<String> suggestedOutcomeIds
    ) {
        Optional<WeeklyPlanEntity> mostRecentReconciled = sortedPlans.stream()
                .filter(p -> p.getState() == PlanState.RECONCILED
                        || p.getState() == PlanState.CARRY_FORWARD)
                .max(Comparator.comparing(WeeklyPlanEntity::getWeekStartDate));

        if (mostRecentReconciled.isEmpty()) {
            return;
        }

        WeeklyPlanEntity reconciledPlan = mostRecentReconciled.get();
        List<WeeklyCommitEntity> reconciledCommits =
                commitsByPlanId.getOrDefault(reconciledPlan.getId(), List.of());
        if (reconciledCommits.isEmpty()) {
            return;
        }

        List<UUID> commitIds = reconciledCommits.stream()
                .map(WeeklyCommitEntity::getId).toList();
        Map<UUID, WeeklyCommitActualEntity> actualsMap = new HashMap<>();
        actualRepository.findByOrgIdAndCommitIdIn(orgId, commitIds)
                .forEach(a -> actualsMap.put(a.getCommitId(), a));

        for (WeeklyCommitEntity commit : reconciledCommits) {
            WeeklyCommitActualEntity actual = actualsMap.get(commit.getId());
            if (actual != null && actual.getCompletionStatus() != CompletionStatus.DONE
                    && !hasSuggestionKey(commit, suggestedTitles, suggestedOutcomeIds)) {
                suggestions.add(toSuggestedCommit(commit, CommitSource.CARRIED_FORWARD));
                recordSuggestionKey(commit, suggestedTitles, suggestedOutcomeIds);
            }
        }
    }

    // ── Recurring pattern detection ───────────────────────────────────────────

    private void collectRecurringSuggestions(
            List<WeeklyPlanEntity> sortedPlans,
            Map<UUID, List<WeeklyCommitEntity>> commitsByPlanId,
            List<SuggestedCommit> suggestions,
            Set<String> suggestedTitles,
            Set<String> suggestedOutcomeIds
    ) {
        if (sortedPlans.size() < 2) {
            return;
        }

        // Compare the two most recent consecutive plans
        WeeklyPlanEntity mostRecent = sortedPlans.get(sortedPlans.size() - 1);
        WeeklyPlanEntity previousPlan = sortedPlans.get(sortedPlans.size() - 2);

        // Only consider truly consecutive weeks
        if (!mostRecent.getWeekStartDate().equals(
                previousPlan.getWeekStartDate().plusWeeks(1))) {
            return;
        }

        List<WeeklyCommitEntity> recentCommits =
                commitsByPlanId.getOrDefault(mostRecent.getId(), List.of());
        List<WeeklyCommitEntity> prevCommits =
                commitsByPlanId.getOrDefault(previousPlan.getId(), List.of());

        for (WeeklyCommitEntity recentCommit : recentCommits) {
            if (hasSuggestionKey(recentCommit, suggestedTitles, suggestedOutcomeIds)) {
                continue; // Already suggested or already present in the draft
            }
            boolean hasMatch = prevCommits.stream()
                    .anyMatch(prev -> areSimilar(recentCommit, prev));
            if (hasMatch) {
                suggestions.add(toSuggestedCommit(recentCommit, CommitSource.RECURRING));
                recordSuggestionKey(recentCommit, suggestedTitles, suggestedOutcomeIds);
            }
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private WeeklyPlanEntity getOrCreateDraftPlan(UUID orgId, UUID userId, LocalDate weekStart) {
        return planRepository.findByOrgIdAndOwnerUserIdAndWeekStartDate(orgId, userId, weekStart)
                .map(existing -> {
                    if (existing.getState() != PlanState.DRAFT) {
                        throw new PlanStateException(
                                ErrorCode.PLAN_NOT_IN_DRAFT,
                                "Cannot add draft suggestions to a plan that is not in DRAFT state",
                                existing.getState().name()
                        );
                    }
                    return existing;
                })
                .orElseGet(() -> {
                    WeeklyPlanEntity newPlan = new WeeklyPlanEntity(
                            UUID.randomUUID(), orgId, userId, weekStart
                    );
                    return planRepository.save(newPlan);
                });
    }

    private SuggestedCommit toSuggestedCommit(WeeklyCommitEntity entity, CommitSource source) {
        return new SuggestedCommit(
                entity.getId(),
                entity.getTitle(),
                entity.getDescription(),
                entity.getChessPriority() != null ? entity.getChessPriority().name() : null,
                entity.getCategory() != null ? entity.getCategory().name() : null,
                entity.getOutcomeId() != null ? entity.getOutcomeId().toString() : null,
                entity.getNonStrategicReason(),
                entity.getExpectedResult(),
                source,
                entity.getId() // sourceCommitId — the historical entity's ID
        );
    }

    private static boolean hasSuggestionKey(
            WeeklyCommitEntity commit,
            Set<String> suggestedTitles,
            Set<String> suggestedOutcomeIds
    ) {
        return hasSuggestionKey(
                commit.getTitle(), commit.getOutcomeId(), suggestedTitles, suggestedOutcomeIds
        );
    }

    private static boolean hasSuggestionKey(
            String title,
            UUID outcomeId,
            Set<String> suggestedTitles,
            Set<String> suggestedOutcomeIds
    ) {
        return suggestedTitles.contains(normalizeTitle(title))
                || (outcomeId != null && suggestedOutcomeIds.contains(outcomeId.toString()));
    }

    private static void recordSuggestionKey(
            WeeklyCommitEntity commit,
            Set<String> suggestedTitles,
            Set<String> suggestedOutcomeIds
    ) {
        recordSuggestionKey(
                commit.getTitle(), commit.getOutcomeId(), suggestedTitles, suggestedOutcomeIds
        );
    }

    private static void recordSuggestionKey(
            String title,
            UUID outcomeId,
            Set<String> suggestedTitles,
            Set<String> suggestedOutcomeIds
    ) {
        suggestedTitles.add(normalizeTitle(title));
        if (outcomeId != null) {
            suggestedOutcomeIds.add(outcomeId.toString());
        }
    }

    private void validateWeekStart(LocalDate weekStart) {
        if (weekStart.getDayOfWeek() != DayOfWeek.MONDAY) {
            throw new PlanValidationException(
                    ErrorCode.INVALID_WEEK_START,
                    "weekStart must be a Monday",
                    List.of(Map.of("provided", weekStart.toString()))
            );
        }
    }

    // ── Similarity utilities (package-private for testing) ────────────────────

    /**
     * Returns {@code true} if two commits are considered similar.
     *
     * <p>Similarity is determined by:
     * <ol>
     *   <li>Identical non-null outcome IDs, OR</li>
     *   <li>Normalized Levenshtein distance between titles below
     *       {@value #SIMILARITY_THRESHOLD}</li>
     * </ol>
     */
    static boolean areSimilar(WeeklyCommitEntity a, WeeklyCommitEntity b) {
        if (a.getOutcomeId() != null && a.getOutcomeId().equals(b.getOutcomeId())) {
            return true;
        }
        return normalizedLevenshteinDistance(a.getTitle(), b.getTitle()) < SIMILARITY_THRESHOLD;
    }

    /**
     * Computes the normalized Levenshtein distance between two strings.
     *
     * <p>Both strings are lowercased and trimmed before comparison.
     * Returns a value in [0.0, 1.0] where 0.0 means identical.
     */
    static double normalizedLevenshteinDistance(String a, String b) {
        String normA = normalizeTitle(a);
        String normB = normalizeTitle(b);
        if (normA.equals(normB)) {
            return 0.0;
        }
        int maxLen = Math.max(normA.length(), normB.length());
        if (maxLen == 0) {
            return 0.0;
        }
        return (double) levenshteinDistance(normA, normB) / maxLen;
    }

    /**
     * Returns a normalized version of a commit title: lowercased, trimmed, and
     * consecutive whitespace collapsed to a single space.
     */
    static String normalizeTitle(String title) {
        if (title == null) {
            return "";
        }
        return title.toLowerCase().trim().replaceAll("\\s+", " ");
    }

    /**
     * Computes the Levenshtein edit distance between two pre-normalized strings
     * using a two-row DP algorithm with O(n) space.
     */
    static int levenshteinDistance(String a, String b) {
        int m = a.length();
        int n = b.length();
        if (m == 0) {
            return n;
        }
        if (n == 0) {
            return m;
        }

        int[] prev = new int[n + 1];
        int[] curr = new int[n + 1];
        for (int j = 0; j <= n; j++) {
            prev[j] = j;
        }

        for (int i = 1; i <= m; i++) {
            curr[0] = i;
            for (int j = 1; j <= n; j++) {
                if (a.charAt(i - 1) == b.charAt(j - 1)) {
                    curr[j] = prev[j - 1];
                } else {
                    curr[j] = 1 + Math.min(prev[j - 1], Math.min(prev[j], curr[j - 1]));
                }
            }
            int[] temp = prev;
            prev = curr;
            curr = temp;
        }

        return prev[n];
    }

    // ── Result type ───────────────────────────────────────────────────────────

    /**
     * The result of a draft-from-history operation: the plan ID for the
     * created/updated DRAFT plan and the ordered list of suggested commits.
     */
    public record DraftFromHistoryResult(
            UUID planId,
            List<SuggestedCommit> suggestedCommits
    ) {
    }
}
