package com.weekly.capacity;

import com.weekly.auth.AuthenticatedUserContext;
import com.weekly.auth.DirectReport;
import com.weekly.auth.OrgGraphClient;
import com.weekly.plan.domain.WeeklyCommitEntity;
import com.weekly.plan.domain.WeeklyPlanEntity;
import com.weekly.plan.repository.WeeklyCommitRepository;
import com.weekly.plan.repository.WeeklyPlanRepository;
import com.weekly.shared.ApiErrorResponse;
import com.weekly.shared.CapacityQualityProvider;
import com.weekly.shared.ErrorCode;
import com.weekly.shared.OvercommitWarning;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller for capacity planning endpoints.
 *
 * <h3>Endpoints</h3>
 * <ul>
 *   <li>{@code GET /api/v1/users/me/capacity} — returns the authenticated user's
 *       most recently computed capacity profile, or 404 if no profile exists yet.</li>
 *   <li>{@code GET /api/v1/team/capacity?weekStart=YYYY-MM-DD} — manager-only view
 *       of each direct report's capacity posture for the requested week.</li>
 * </ul>
 *
 * <p>The caller's identity ({@code orgId}, {@code userId}) is sourced exclusively
 * from the validated {@link com.weekly.auth.UserPrincipal} exposed through the
 * request-scoped {@link AuthenticatedUserContext} (§9.1).
 */
@RestController
@RequestMapping("/api/v1")
public class CapacityController {

    private final AuthenticatedUserContext authenticatedUserContext;
    private final CapacityProfileService capacityProfileService;
    private final CapacityQualityProvider capacityQualityProvider;
    private final WeeklyPlanRepository weeklyPlanRepository;
    private final WeeklyCommitRepository weeklyCommitRepository;
    private final OrgGraphClient orgGraphClient;
    private final OvercommitDetector overcommitDetector;

    public CapacityController(
            AuthenticatedUserContext authenticatedUserContext,
            CapacityProfileService capacityProfileService,
            CapacityQualityProvider capacityQualityProvider,
            WeeklyPlanRepository weeklyPlanRepository,
            WeeklyCommitRepository weeklyCommitRepository,
            OrgGraphClient orgGraphClient,
            OvercommitDetector overcommitDetector) {
        this.authenticatedUserContext = authenticatedUserContext;
        this.capacityProfileService = capacityProfileService;
        this.capacityQualityProvider = capacityQualityProvider;
        this.weeklyPlanRepository = weeklyPlanRepository;
        this.weeklyCommitRepository = weeklyCommitRepository;
        this.orgGraphClient = orgGraphClient;
        this.overcommitDetector = overcommitDetector;
    }

    /**
     * GET /api/v1/users/me/capacity
     *
     * <p>Returns the authenticated user's most recently computed capacity profile.
     *
     * @return 200 with {@link CapacityProfileResponse}, or 404 if no profile has been
     *         computed yet (the profile is generated by the weekly
     *         {@link CapacityComputeJob})
     */
    @GetMapping("/users/me/capacity")
    public ResponseEntity<?> getMyCapacity() {
        UUID orgId = authenticatedUserContext.orgId();
        UUID userId = authenticatedUserContext.userId();

        return capacityProfileService.getProfile(orgId, userId)
                .<ResponseEntity<?>>map(profile ->
                        ResponseEntity.ok(CapacityProfileResponse.from(profile)))
                .orElseGet(() -> ResponseEntity
                        .status(ErrorCode.NOT_FOUND.getHttpStatus())
                        .body(ApiErrorResponse.of(
                                ErrorCode.NOT_FOUND,
                                "No capacity profile found for user " + userId)));
    }

    /**
     * GET /api/v1/team/capacity?weekStart=YYYY-MM-DD
     *
     * <p>Returns the capacity posture of every direct report of the authenticated
     * manager for the requested week. For each team member the response includes:
     * <ul>
     *   <li>raw estimated hours (sum of all commit estimates)</li>
     *   <li>bias-adjusted estimated hours (corrected using historical accuracy)</li>
     *   <li>realistic weekly cap (p50 of historical actual hours)</li>
     *   <li>overcommit severity level ({@code NONE}, {@code MODERATE}, or {@code HIGH})</li>
     * </ul>
     *
     * <p>Requires the {@code MANAGER} role; returns 403 otherwise.
     *
     * @param weekStart ISO-8601 Monday date string (e.g. {@code 2026-03-16})
     * @return 200 with {@link TeamCapacityResponse}, or 403 if the caller lacks the
     *         MANAGER role
     */
    @GetMapping("/team/capacity")
    public ResponseEntity<?> getTeamCapacity(@RequestParam String weekStart) {
        if (!authenticatedUserContext.isManager()) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN)
                    .body(ApiErrorResponse.of(
                            ErrorCode.FORBIDDEN,
                            "Manager role required"));
        }

        UUID orgId = authenticatedUserContext.orgId();
        UUID managerId = authenticatedUserContext.userId();
        LocalDate weekStartDate = LocalDate.parse(weekStart);

        // 1. Resolve direct reports with display names
        List<DirectReport> directReports =
                orgGraphClient.getDirectReportsWithNames(orgId, managerId);
        List<UUID> directReportIds =
                directReports.stream().map(DirectReport::userId).toList();

        // 2. Load plans for all direct reports in the requested week
        List<WeeklyPlanEntity> plans = directReportIds.isEmpty()
                ? List.of()
                : weeklyPlanRepository.findByOrgIdAndWeekStartDateAndOwnerUserIdIn(
                        orgId, weekStartDate, directReportIds);
        Map<UUID, WeeklyPlanEntity> plansByUser = plans.stream()
                .collect(Collectors.toMap(
                        WeeklyPlanEntity::getOwnerUserId, Function.identity()));

        // 3. Load commits for all plans in a single batch query
        List<UUID> planIds = plans.stream().map(WeeklyPlanEntity::getId).toList();
        List<WeeklyCommitEntity> allCommits = planIds.isEmpty()
                ? List.of()
                : weeklyCommitRepository.findByOrgIdAndWeeklyPlanIdIn(orgId, planIds);
        Map<UUID, List<WeeklyCommitEntity>> commitsByPlan = allCommits.stream()
                .collect(Collectors.groupingBy(WeeklyCommitEntity::getWeeklyPlanId));

        // 4. Build per-member capacity summary
        List<TeamMemberCapacity> members = directReports.stream()
                .map(report -> buildMemberCapacity(
                        report, orgId, plansByUser, commitsByPlan))
                .toList();

        return ResponseEntity.ok(new TeamCapacityResponse(weekStart, members));
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Builds the capacity summary for a single direct report.
     *
     * <p>Loads the user's capacity profile (if available) and runs
     * {@link OvercommitDetector} against their commits for the week.
     */
    private TeamMemberCapacity buildMemberCapacity(
            DirectReport report,
            UUID orgId,
            Map<UUID, WeeklyPlanEntity> plansByUser,
            Map<UUID, List<WeeklyCommitEntity>> commitsByPlan) {

        WeeklyPlanEntity plan = plansByUser.get(report.userId());
        List<WeeklyCommitEntity> commits = plan == null
                ? List.of()
                : commitsByPlan.getOrDefault(plan.getId(), List.of());

        // Sum raw estimated hours across all commits
        BigDecimal estimatedHours = commits.stream()
                .filter(c -> c.getEstimatedHours() != null)
                .map(WeeklyCommitEntity::getEstimatedHours)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Load capacity profile and run overcommit detection
        CapacityProfileEntity profile =
                capacityProfileService.getProfile(orgId, report.userId()).orElse(null);
        OvercommitWarning warning =
                overcommitDetector.detectOvercommitment(commits, profile);

        BigDecimal realisticCap = profile != null ? profile.getRealisticWeeklyCap() : null;
        BigDecimal adjustedEstimate = hasUsableCapacityProfile(profile)
                ? warning.adjustedTotal()
                : estimatedHours;

        return new TeamMemberCapacity(
                report.userId().toString(),
                report.displayName(),
                estimatedHours,
                adjustedEstimate,
                realisticCap,
                warning.level().name());
    }

    private static boolean hasUsableCapacityProfile(CapacityProfileEntity profile) {
        return profile != null
                && profile.getRealisticWeeklyCap() != null
                && profile.getRealisticWeeklyCap().compareTo(BigDecimal.ZERO) > 0
                && profile.getWeeksAnalyzed() > 0;
    }
}
