/**
 * Standardized API error codes from the PRD (Appendix A).
 *
 * All error responses follow the envelope:
 * { "error": { "code": "...", "message": "...", "details": [...] } }
 */
export enum ErrorCode {
  // 400
  MISSING_IDEMPOTENCY_KEY = "MISSING_IDEMPOTENCY_KEY",

  // 401
  UNAUTHORIZED = "UNAUTHORIZED",

  // 404
  NOT_FOUND = "NOT_FOUND",

  // 403
  FORBIDDEN = "FORBIDDEN",

  // 409
  CONFLICT = "CONFLICT",
  FIELD_FROZEN = "FIELD_FROZEN",
  PLAN_NOT_IN_DRAFT = "PLAN_NOT_IN_DRAFT",
  CARRY_FORWARD_ALREADY_EXECUTED = "CARRY_FORWARD_ALREADY_EXECUTED",

  // 422
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MISSING_CHESS_PRIORITY = "MISSING_CHESS_PRIORITY",
  MISSING_RCDO_OR_REASON = "MISSING_RCDO_OR_REASON",
  CONFLICTING_LINK = "CONFLICTING_LINK",
  CHESS_RULE_VIOLATION = "CHESS_RULE_VIOLATION",
  MISSING_DELTA_REASON = "MISSING_DELTA_REASON",
  MISSING_COMPLETION_STATUS = "MISSING_COMPLETION_STATUS",
  INVALID_WEEK_START = "INVALID_WEEK_START",
  PAST_WEEK_CREATION_BLOCKED = "PAST_WEEK_CREATION_BLOCKED",
  RCDO_VALIDATION_STALE = "RCDO_VALIDATION_STALE",
  IDEMPOTENCY_KEY_REUSE = "IDEMPOTENCY_KEY_REUSE",

  // 500
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  // 503
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
}

/** HTTP status associated with each error code */
export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  [ErrorCode.MISSING_IDEMPOTENCY_KEY]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.FIELD_FROZEN]: 409,
  [ErrorCode.PLAN_NOT_IN_DRAFT]: 409,
  [ErrorCode.CARRY_FORWARD_ALREADY_EXECUTED]: 409,
  [ErrorCode.VALIDATION_ERROR]: 422,
  [ErrorCode.MISSING_CHESS_PRIORITY]: 422,
  [ErrorCode.MISSING_RCDO_OR_REASON]: 422,
  [ErrorCode.CONFLICTING_LINK]: 422,
  [ErrorCode.CHESS_RULE_VIOLATION]: 422,
  [ErrorCode.MISSING_DELTA_REASON]: 422,
  [ErrorCode.MISSING_COMPLETION_STATUS]: 422,
  [ErrorCode.INVALID_WEEK_START]: 422,
  [ErrorCode.PAST_WEEK_CREATION_BLOCKED]: 422,
  [ErrorCode.RCDO_VALIDATION_STALE]: 422,
  [ErrorCode.IDEMPOTENCY_KEY_REUSE]: 422,
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
};
