/**
 * @weekly-commitments/contracts
 *
 * Shared TypeScript type definitions and enumerations for the
 * Weekly Commitments module. Both the micro-frontend and the
 * PA host stub consume these types.
 */

export { PlanState, ReviewStatus, ChessPriority, CompletionStatus, LockType, CommitCategory } from "./enums.js";

export type {
  WeeklyPlan,
  WeeklyCommit,
  WeeklyCommitActual,
  ManagerReview,
  RcdoOutcome,
  RcdoObjective,
  RcdoCry,
  ValidationError,
  TrendSeverity,
  TrendInsight,
  WeekTrendPoint,
  TrendsResponse,
  NextWorkSource,
  NextWorkSuggestion,
  SuggestNextWorkRequest,
  SuggestNextWorkResponse,
  NextWorkSuggestionsResponse,
  SuggestionFeedbackAction,
  SuggestionFeedbackRequest,
  SuggestionFeedbackResponse,
  CheckInStatus,
  CheckInEntry,
  CheckInHistoryResponse,
} from "./types.js";

export { ErrorCode, ERROR_HTTP_STATUS } from "./errors.js";
export type { ApiError, ApiErrorDetail, ApiErrorResponse } from "./api.js";

export { EventType, AggregateType, NotificationType } from "./events.js";
export type { OutboxEvent } from "./events.js";

export type {
  OutcomeCoverageWeek,
  OutcomeCoverageTimeline,
  HeatmapCell,
  HeatmapUser,
  CarryForwardHeatmap,
  UserCategoryShift,
  CategoryShift,
  CategoryShiftAnalysis,
  UserEstimationAccuracy,
  EstimationAccuracyDistribution,
  Prediction,
  UserPredictions,
} from "./analytics.js";

export { createWeeklyCommitmentsClient } from "./client.js";
export type {
  WeeklyCommitmentsClient,
  WeeklyCommitmentsClientOptions,
  WeeklyCommitmentsApiPaths,
  WeeklyCommitmentsApiComponents,
  WeeklyCommitmentsApiOperations,
} from "./client.js";

export type {
  CreatePlanRequest,
  LockPlanRequest,
  StartReconciliationRequest,
  SubmitReconciliationRequest,
  CarryForwardRequest,
  CreateCommitRequest,
  UpdateCommitRequest,
  UpdateActualRequest,
  CheckInRequest,
  QuickUpdateNoteSource,
  QuickUpdateItem,
  QuickUpdateRequest,
  QuickUpdateResponse,
  CheckInOptionRequest,
  CheckInOptionItem,
  CheckInOptionsResponse,
  ReviewStatusCounts,
  TeamMemberSummary,
  TeamSummaryResponse,
  ReviewDecision,
  CreateReviewRequest,
  RcdoRollupItem,
  RcdoRollupResponse,
  NotificationItem,
  RcdoTreeResponse,
  RcdoSearchResult,
  RcdoSearchResponse,
  SuggestRcdoRequest,
  RcdoSuggestion,
  AiSuggestionStatus,
  SuggestRcdoResponse,
  DraftReconciliationRequest,
  ReconciliationDraftItem,
  DraftReconciliationResponse,
  ManagerInsightsRequest,
  ManagerInsightItem,
  ManagerInsightsResponse,
  QualityNudge,
  PlanQualityCheckRequest,
  PlanQualityCheckResponse,
  CommitSourceType,
  SuggestedCommit,
  DraftFromHistoryRequest,
  DraftFromHistoryResponse,
  TrendDirection,
  PerformanceProfile,
  UserPreferences,
  UserTrends,
  UserProfileResponse,
  OutcomeProgressType,
  OutcomeUrgencyBand,
  StrategicSlackBand,
  MilestoneStatus,
  Milestone,
  OutcomeMetadataRequest,
  OutcomeMetadataResponse,
  ProgressUpdateRequest,
  UrgencyInfo,
  SlackInfo,
  UrgencySummaryResponse,
  StrategicSlackResponse,
  CapacityConfidenceLevel,
  OvercommitLevel,
  CapacityProfile,
  CapacityProfileResponse,
  TeamMemberCapacity,
  TeamCapacityResponse,
  CategoryInsight,
  PriorityInsight,
  EstimationCoachingResponse,
  OrgPolicy,
  UpdateDigestConfigRequest,
  WeeklyAdoptionPoint,
  AdoptionMetrics,
  AiUsageMetrics,
  OutcomeHealthItem,
  RcdoHealthReport,
  PaginatedResponse,
  IntegrationProvider,
  LinkTicketRequest,
  ExternalTicketLink,
  LinkedTicketsResponse,
  WebhookResponse,
} from "./api.js";
