/**
 * @weekly-commitments/contracts
 *
 * Shared TypeScript type definitions and enumerations for the
 * Weekly Commitments module. Both the micro-frontend and the
 * PA host stub consume these types.
 */

export {
  PlanState,
  ReviewStatus,
  ChessPriority,
  CompletionStatus,
  LockType,
  CommitCategory,
  EffortType,
  IssueStatus,
  TeamRole,
  AccessRequestStatus,
  IssueActivityType,
} from "./enums.js";

export type {
  WeeklyPlan,
  WeeklyCommit,
  WeeklyCommitActual,
  ManagerReview,
  RcdoOutcome,
  RcdoObjective,
  RcdoCry,
  ValidationError,
  TrendSeverity,
  TrendInsight,
  WeekTrendPoint,
  TrendsResponse,
  NextWorkSource,
  NextWorkSuggestion,
  SuggestNextWorkRequest,
  SuggestNextWorkResponse,
  NextWorkSuggestionsResponse,
  SuggestionFeedbackAction,
  SuggestionFeedbackRequest,
  SuggestionFeedbackResponse,
  CheckInStatus,
  CheckInEntry,
  CheckInHistoryResponse,
  Issue,
  WeeklyAssignment,
  WeeklyAssignmentActual,
  IssueActivity,
  Team,
  TeamMember,
  TeamAccessRequest,
} from "./types.js";

export { ErrorCode, ERROR_HTTP_STATUS } from "./errors.js";
export type { ApiError, ApiErrorDetail, ApiErrorResponse } from "./api.js";

export { EventType, AggregateType, NotificationType } from "./events.js";
export type { OutboxEvent } from "./events.js";

export type {
  OutcomeCoverageWeek,
  OutcomeCoverageTimeline,
  HeatmapCell,
  HeatmapUser,
  CarryForwardHeatmap,
  UserCategoryShift,
  CategoryShift,
  CategoryShiftAnalysis,
  UserEstimationAccuracy,
  EstimationAccuracyDistribution,
  Prediction,
  UserPredictions,
} from "./analytics.js";

export { createWeeklyCommitmentsClient } from "./client.js";
export type {
  WeeklyCommitmentsClient,
  WeeklyCommitmentsClientOptions,
  WeeklyCommitmentsApiPaths,
  WeeklyCommitmentsApiComponents,
  WeeklyCommitmentsApiOperations,
} from "./client.js";

export type {
  CreatePlanRequest,
  LockPlanRequest,
  StartReconciliationRequest,
  SubmitReconciliationRequest,
  CarryForwardRequest,
  CreateCommitRequest,
  UpdateCommitRequest,
  UpdateActualRequest,
  CheckInRequest,
  QuickUpdateNoteSource,
  QuickUpdateItem,
  QuickUpdateRequest,
  QuickUpdateResponse,
  CheckInOptionRequest,
  CheckInOptionSource,
  CheckInOptionItem,
  CheckInOptionsResponse,
  ReviewStatusCounts,
  TeamMemberSummary,
  TeamSummaryResponse,
  ReviewDecision,
  CreateReviewRequest,
  RcdoRollupItem,
  RcdoRollupResponse,
  NotificationTypeValue,
  WeeklyPlanDraftReadyNotificationPayload,
  PlanMisalignmentBriefingNotificationPayload,
  NotificationItem,
  RcdoTreeResponse,
  RcdoSearchResult,
  RcdoSearchResponse,
  SuggestRcdoRequest,
  RcdoSuggestion,
  AiSuggestionStatus,
  SuggestRcdoResponse,
  DraftReconciliationRequest,
  ReconciliationDraftItem,
  DraftReconciliationResponse,
  ManagerInsightsRequest,
  ManagerInsightItem,
  ManagerInsightsResponse,
  QualityNudge,
  PlanQualityCheckRequest,
  PlanQualityCheckResponse,
  CommitSourceType,
  SuggestedCommit,
  DraftFromHistoryRequest,
  DraftFromHistoryResponse,
  TrendDirection,
  PerformanceProfile,
  UserPreferences,
  UserTrends,
  UserProfileResponse,
  OutcomeProgressType,
  OutcomeUrgencyBand,
  StrategicSlackBand,
  MilestoneStatus,
  Milestone,
  OutcomeMetadataRequest,
  OutcomeMetadataResponse,
  ProgressUpdateRequest,
  UrgencyInfo,
  SlackInfo,
  UrgencySummaryResponse,
  StrategicSlackResponse,
  ForecastConfidenceBand,
  ForecastStatus,
  OutcomeForecastFactor,
  OutcomeForecastResponse,
  OutcomeForecastListResponse,
  TeamPlanSuggestionRequest,
  TeamPlanSuggestionUnavailableResponse,
  TeamPlanSummary,
  MemberOutcomeSlice,
  OutcomeAllocationSuggestion,
  PlanningCopilotSuggestedCommit,
  TeamMemberPlanSuggestion,
  TeamPlanSuggestionResponse,
  SuggestedCommitApplyRequest,
  TeamMemberApplyRequest,
  ApplyTeamPlanSuggestionRequest,
  MemberDraftApplyResult,
  ApplyTeamPlanSuggestionResponse,
  ExecutiveDashboardUnavailableResponse,
  ExecutiveSummary,
  RallyCryHealthRollup,
  TeamBucketComparison,
  ExecutiveDashboardResponse,
  ExecutiveBriefingRequest,
  ExecutiveBriefingItem,
  ExecutiveBriefingResponse,
  CapacityConfidenceLevel,
  OvercommitLevel,
  CapacityProfile,
  CapacityProfileResponse,
  TeamMemberCapacity,
  TeamCapacityResponse,
  CategoryInsight,
  PriorityInsight,
  EstimationCoachingResponse,
  OrgPolicy,
  UpdateDigestConfigRequest,
  WeeklyAdoptionPoint,
  AdoptionMetrics,
  AiUsageMetrics,
  OutcomeHealthItem,
  RcdoHealthReport,
  PaginatedResponse,
  IntegrationProvider,
  LinkTicketRequest,
  ExternalTicketLink,
  LinkedTicketsResponse,
  WebhookResponse,
  // Phase 6
  CreateIssueRequest,
  UpdateIssueRequest,
  IssueListResponse,
  IssueDetailResponse,
  AssignIssueRequest,
  CommitIssueToWeekRequest,
  CreateWeeklyAssignmentRequest,
  ReleaseIssueRequest,
  AddCommentRequest,
  LogTimeEntryRequest,
  WeeklyAssignmentWithActual,
  WeeklyAssignmentsResponse,
  CreateTeamRequest,
  UpdateTeamRequest,
  AddTeamMemberRequest,
  TeamListResponse,
  TeamDetailResponse,
  TeamAccessRequestAction,
  TeamAccessRequestListResponse,
  SuggestEffortTypeRequest,
  SuggestEffortTypeResponse,
  RankBacklogRequest,
  RankedIssue,
  RankBacklogResponse,
  RecommendWeeklyIssuesRequest,
  RecommendedIssue,
  RecommendWeeklyIssuesResponse,
  SuggestDeferralsRequest,
  DeferralSuggestion,
  SuggestDeferralsResponse,
  CoverageGapInspirationItem,
  CoverageGapInspirationsResponse,
  SemanticSearchRequest,
  SemanticSearchHit,
  SemanticSearchResponse,
} from "./api.js";
